sudo: required
language: python
services:
  - docker
before_install:
  - docker pull quay.io/fenicsproject/stable:current
script:
  - docker run -v $(pwd):/shared quay.io/fenicsproject/stable:current python3 test.py
